### ISSUE TITLE
time-format for ISO 8601 is not working

### ISSUE THREAD

**Issue by LukasJerabek** [qiangyt/jog#49]
Hi, I have tried using this format on repl.it (time.Parse("2006-01-02T15:04:05-0700", <my_timestamp>)) and it worked, so am I doing something wrong here in config or is this not working yet?

Settings:
version v1.0.1-alpha
json format log files
custom config since time and level keys are different

input file log example:
`{"asctime":"2021-03-04T07:59:25+0100","levelname":"INFO","name":"some_component","filename":"some_file","message":"some_message"}`

jog output:
```
1      2021-03-04T07:59:25+0100 - INFO - some_component - some_file:
some_message
```

My config:
```
Config file 
colorization: true
pattern: "${timestamp} - ${level} - ${app} - ${file}:${message}${stacktrace}${others}"

line-no:
  print: true
  color: FgRed
  print-format: "\n%s"

unknown-line:
  print: true
  color: FgGray

fields:
  others:
    name:
      color: FgYellow
    separator:
      label: =
      color: FgDefault
    value:
      color: FgDefault
    print-format: "\n%s"
  level: # 'level' field is a hard-coded field used for level filter as well, so don't rename it
         # And, it must be an enum.
    print-format: "%s" # follows https://golang.org/pkg/fmt/
    alias: "levelname"
    case-sensitive: false
    enums:
      case-sensitive: false
      NOTSET:
        alias: notset,0
        color: FgGray,OpBold
      DEBUG:
        alias: debug,10
        color: FgGreen,OpBold
      INFO:
        alias: info,20,
        color: FgBlue,OpBold,OpFuzzy
      WARNING:
        alias: warn,warning,30
        color: FgYellow,OpBold
      ERROR:
        alias: error,err,40
        color: FgMagenta,OpBold
      CRITICAL:
        alias: critical,50
        color: FgRed,OpBold
  app:
    print: false
    alias: "name"
    case-sensitive: false
    color: FgLightBlue
  file:
    alias: "filename"
    case-sensitive: false
    color: FgDefault
  message:
    alias: "message"
    case-sensitive: false
    color: FgCyan,OpItalic
    print-format: "\n%s"
  stacktrace:
    alias: "exc_info"
    case-sensitive: false
    color: FgDefault
    print-format: "\nStack trace: \n%s"
  timestamp: # 'timestamp' field is a hard-coded field used for time range filter as well, so don't rename it
    alias: "asctime"
    case-sensitive: false
    color: FgYellow
    type: time
    time-format: "2006-01-02T15:04:05-0700"
```

**Comment by qiangyt** [comment]
@LukasJerabek , what's your expected output?
 
By design, 'time-format' attribute is used only for parsing, not formatting. Jog doesn't do time format conversion.

**Comment by LukasJerabek** [comment]
I have expected something like [this](https://replit.com/@LukasJerabekCZ/OlivedrabTotalCryptos#main.go) to see in the records. But I think I missunderstood its purpose. I think we can close this...

**Comment by qiangyt** [comment]
More explanation:
- timestamp field is always outputted without any conversion, even 'time-format' attribute is specified.
- 'time-format' attribute is used to parse: --after filter value, --before filter value, and timestamp field value. Parsing only occurs if --after/--before filter is specified.
- for many time formats, 'time-format' customization is not needed, because jog will try to do parsing by github.com/araddon/dateparse.

**Comment by qiangyt** [comment]
@LukasJerabek,

I think yes the attribute naming is misleading. I won't rename it but I will add comments to default template.
Another question is, do you think it makes sense to add a timestamp value conversion feature?

**Comment by LukasJerabek** [comment]
Thank you for explanation. Might make, sometimes it would slightly improve readibility. Its not critical, but maybe nice-to-have feature.
